# Generated by Django 4.0.4 on 2022-05-11 17:07

import conteiners.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_cliente', models.CharField(max_length=255, unique=True)),
                ('id_do_cliente', models.CharField(max_length=8, unique=True, validators=[conteiners.validators.valida_id])),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
