# Generated by Django 4.0.4 on 2022-05-11 18:52

import conteiners.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteiners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conteiner', models.CharField(max_length=11, unique=True, validators=[conteiners.validators.valida_conteiner])),
                ('tipo_conteiner', models.CharField(choices=[('20', '20'), ('40', '40')], max_length=2)),
                ('status_conteiner', models.CharField(choices=[('CHEIO', 'Cheio'), ('VAZIO', 'Vazio')], max_length=5)),
                ('categoria_conteiner', models.CharField(choices=[('IMPORTACAO', 'Importação'), ('EXPORTACAO', 'Exportação')], max_length=11)),
                ('cliente_conteiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteiners.cliente')),
            ],
            options={
                'db_table': 'conteiner',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('EMBARQUE', 'Embarque'), ('DESCARGA', 'Descarga'), ('GATE IN', 'Gate In'), ('GATE OUT', 'Gate Out'), ('REPOSICIONAMENTO', 'Repoosicionamento'), ('PESAGEM', 'Pesagem'), ('SCANNER', 'Scanner')], max_length=16)),
                ('data_hora_início', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('cliente_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteiners.cliente')),
                ('conteiner_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteiners.conteiner')),
            ],
            options={
                'db_table': 'movimentacao',
            },
        ),
    ]
