# Generated by Django 4.0.4 on 2022-05-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteiners', '0002_conteiner_movimentacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='data_hora_início',
            new_name='data_hora_inicio',
        ),
    ]
